Revert "GC.enable"
This reverts commit df15dac45e56268cb8a7bfb073e165ef2abf5c0b.

I'm so sorry... :cry:

Error case 1:
zsh: bus error

Error case 2:
trace:
        [0] /home/mruby/code/mrblib/mitamae/recipe_executor.rb:32:in MItamae::RecipeExecutor.execute_children
        [1] /home/mruby/code/mrblib/mitamae/logger.rb:97:in MItamae::Logger.with_indent
        [2] /home/mruby/code/mrblib/mitamae/recipe_executor.rb:31:in MItamae::RecipeExecutor.execute_children
        [3] /home/mruby/code/mrblib/mitamae/recipe_executor.rb:19:in MItamae::RecipeExecutor.execute_node
        [4] /home/mruby/code/mrblib/mitamae/recipe_executor.rb:33:in MItamae::RecipeExecutor.execute_children
        [5] /home/mruby/code/mruby/mrblib/array.rb:17:in Array.each
        [6] /home/mruby/code/mrblib/mitamae/recipe_executor.rb:32:in MItamae::RecipeExecutor.execute_children
        [7] /home/mruby/code/mrblib/mitamae/logger.rb:97:in MItamae::Logger.with_indent
        [8] /home/mruby/code/mrblib/mitamae/recipe_executor.rb:31:in MItamae::RecipeExecutor.execute_children
        [9] /home/mruby/code/mrblib/mitamae/recipe_executor.rb:19:in MItamae::RecipeExecutor.execute_node
        [10] /home/mruby/code/mrblib/mitamae/recipe_executor.rb:33:in MItamae::RecipeExecutor.execute_children
        [11] /home/mruby/code/mruby/mrblib/array.rb:17:in Array.each
        [12] /home/mruby/code/mrblib/mitamae/recipe_executor.rb:32:in MItamae::RecipeExecutor.execute_children
        [13] /home/mruby/code/mrblib/mitamae/logger.rb:97:in MItamae::Logger.with_indent
        [14] /home/mruby/code/mrblib/mitamae/recipe_executor.rb:31:in MItamae::RecipeExecutor.execute_children
        [15] /home/mruby/code/mrblib/mitamae/recipe_executor.rb:19:in MItamae::RecipeExecutor.execute_node
        [16] /home/mruby/code/mrblib/mitamae/recipe_executor.rb:9:in MItamae::RecipeExecutor.execute
        [17] /home/mruby/code/mruby/mrblib/array.rb:17:in Array.each
        [18] /home/mruby/code/mrblib/mitamae/recipe_executor.rb:8:in MItamae::RecipeExecutor.execute
        [19] /home/mruby/code/mrblib/mitamae/cli/local.rb:37:in MItamae::CLI::Local.run
        [20] /home/mruby/code/mrblib/mitamae/cli.rb:17:in MItamae::CLI.run
        [21] /home/mruby/code/mrblib/mitamae/cli.rb:4:in MItamae::CLI#start
        [22] /home/mruby/code/mrblib/mitamae.rb:2:in Object.__main__
/home/mruby/code/mrblib/mitamae/recipe_executor.rb:32: undefined method 'each' for "MItamae::RecipeExecutor" (NoMethodError)